---

- include_tasks:
    file: _task_header.yml
  vars:
    kol_utils_name: "apt upgrade"
    kol_utils_params:
      hold_ubuntu_pi_incompatibles: "{{ hold_ubuntu_pi_incompatibles| default(True) }}"
      remove_ubuntu_auto_upgrades:  "{{ remove_ubuntu_auto_upgrades | default(True) }}"

########################################

- block:
  - name: "hold ubuntu packages which cant upgrade on pi"
    block:
      - name: "Get held packages"
        become: yes
        command: apt-mark showhold
        register: held_packages
        changed_when: false

      - name: "hold linux-firmware"
        become: yes
        command: apt-mark hold linux-firmware
        when: "'linux-firmware' not in held_packages.stdout"

      - name: "unhold flash-kernel"
        become: yes
        command: apt-mark unhold flash-kernel
        when: "'flash-kernel' in held_packages.stdout"
    when: _params['hold_ubuntu_pi_incompatibles']

  - block:
    - name: "kill unattended upgrade process"
      become: yes
      shell: "pgrep unattended-upgr && pkill -9 unattended-upgr || true"

    - name: "uninstall ubuntu auto upgrades"
      become: yes
      register: uninstall_result
      notify: Reboot
      retries: 3
      delay: 5
      until: uninstall_result is not failed
      apt:
        force_apt_get: yes # there's no need to use aptitude
        name: ["flash-kernel", "unattended-upgrades", "ubuntu-release-upgrader-core"]
        state: absent
      tags: pi_setup
  when: (True if (ansible_distribution=='Ubuntu') else False)

- name: "Upgrade all packages to the latest version"
  become: yes
  register: upgrade_result
  notify: Reboot
  async: 600
  poll: 10
  retries: 3
  delay: 5
  until: upgrade_result is not failed
  apt:
    force_apt_get: yes # there's no need to use aptitude
    update_cache: yes
    cache_valid_time: 3600 # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    name: "*"
    state: latest

- name: "Remove dependencies that are no longer required"
  become: yes
  register: autoremove_result
  notify: Reboot
  async: 600
  poll: 10
  retries: 3
  delay: 5
  until: autoremove_result is not failed
  apt:
    force_apt_get: yes # there's no need to use aptitude
    autoremove: yes

########################################

- include_tasks:
    file: _task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "uninstall_result:  {{ uninstall_result }}",
        "upgrade_result:    {{ upgrade_result }}",
        "autoremove_result: {{ autoremove_result }}"
      ]
