---

- include_tasks:
    file: _task_header.yml
  vars:
    kol_utils_name: "apt raw upgrade"
    kol_utils_params: {}

########################################

- name: "Upgrade all packages to the latest version"
  become: yes
  register: upgrade_result
  notify: Reboot
  async: 600
  poll: 10
  retries: 3
  delay: 5
  until: upgrade_result is not failed
  apt:
    force_apt_get: yes # there's no need to use aptitude
    update_cache: yes
    cache_valid_time: 3600 # Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    name: "*"
    state: latest

- name: "Remove dependencies that are no longer required"
  become: yes
  register: autoremove_result
  notify: Reboot
  async: 600
  poll: 10
  retries: 3
  delay: 5
  until: autoremove_result is not failed
  apt:
    force_apt_get: yes # there's no need to use aptitude
    autoremove: yes

########################################

- include_tasks:
    file: _task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "upgrade_result:    {{ upgrade_result }}",
        "autoremove_result: {{ autoremove_result }}"
      ]
