---

- include_tasks:
    file: task_header.yml
  vars:
    kol_utils_name: "ext4 make filesystem"
    kol_utils_params:
      filesystem_device:     "{{ filesystem_device | mandatory }}"
      filesystem_force_make: "{{ filesystem_force_make | default('False') }}" 

########################################

- name: "make ext4 filesystem on iscsi device"
  become: yes
  register: mkfs_result
  filesystem:
    fstype: ext4
    dev: "{{ _params['filesystem_device'] }}"
    force: "{{ _params['filesystem_force_make'] }}" 

# do not combine with creation above, filesystem module does not support
# create and resize - if both options given, it will only do resize
- name: "expand ext4 filesystem to whole iscsi device"
  become: yes
  register: mkfs_resize_result
  filesystem:
    fstype: ext4
    dev: "{{ _params['filesystem_device'] }}"
    resizefs: yes
  when: mkfs_result.changed

########################################

- include_tasks:
    file: task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "mkfs_result:        {{ mkfs_result }}",
        "mkfs_resize_result: {{ mkfs_resize_result }}"
      ]
