---

- include_tasks:
    file: task_header.yml
  vars:
    kol_utils_name: "iscsi set initiatorname"
    kol_utils_params:
      iscsi_initiatorname: "{{ iscsi_initiatorname | mandatory | replace('{{ inventory_hostname }}',inventory_hostname) }}"

########################################

- name: "Set iscsi initiator name"
  become: yes
  notify: "Reboot"
  lineinfile:
    path: "/etc/iscsi/initiatorname.iscsi"
    regexp: '^(InitiatorName|GenerateName)=.*'
    line: "InitiatorName={{ _params['iscsi_initiatorname'] }}"

########################################

- include_tasks:
    file: task_footer.yml
  vars:
    kol_utils_exit_vars: []
