---
- include_tasks:
    file: _task_header.yml
  vars:
    kol_utils_name: "nfs server restart"
    kol_utils_params: {}

########################################

- name: Reload exports
  become: yes
  command: exportfs -a

- name: Restart nfs server
  run_once: yes
  become: yes
  register: restart_result
  systemd:
    state: restarted
    name: nfs-kernel-server
    daemon_reload: yes

########################################

- include_tasks:
    file: _task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "restart_result: {{ restart_result }}"
      ]
