---

- include_tasks:
    file: _task_header.yml
  vars:
    kol_utils_name: "ntp set servers"
    kol_utils_params:
      ntp_servers: "{{ ntp_servers | mandatory }}"

########################################

- name: "set ntp server"
  become: yes
  notify: Restart ntp
  register: ntp_config_result
  lineinfile:
    path: "/etc/systemd/timesyncd.conf"
    line: "NTP={{ _params['ntp_servers'] }}"
    regexp: "^\\s*#?\\s*(NTP=).*$"
    insertafter: "\\[Time\\]"
    state: present
  when: ntp_servers is defined

########################################

- include_tasks:
    file: _task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "ntp_config_result: {{ ntp_config_result }}"
      ]

