---

- include_tasks:
    file: task_header.yml
  vars:
    kol_utils_name: "pi trafficlight leds"
    kol_utils_params: {}

########################################

- name: "Copy leds utility script"
  become: yes
  copy:
    src: "files/pi-leds"
    dest: "/etc/init.d/pi-leds"
    mode: "755"
  tags: trafficlight_leds

- name: "run update-rc.d"
  become: yes
  register: update_result
  shell:
    chdir: "/etc/init.d"
    cmd: "update-rc.d pi-leds defaults; ./pi-leds start"
    creates: "/etc/rc5.d/S01pi-leds"
    warn: no
  tags: trafficlight_leds

########################################

- include_tasks:
    file: task_footer.yml
  vars:
    kol_utils_exit_vars:
      [
        "update_result: {{ update_result }}"
      ]
