---

- include_tasks:
    file: task_header.yml
  vars:
    kol_utils_name: "REBOOT"
    kol_utils_params: {}

########################################

- name: "trigger reboot"
  become: yes
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  tags: reboot

- name: "await reboot"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300

###################################
#
#   tasks
#
###################################

########################################

- include_tasks:
    file: task_footer.yml
  vars:
    kol_utils_exit_vars: []
