---

- include_tasks:
    file: _task_header.yml
  vars:
    kol_utils_name: "SHUTDOWN"
    kol_utils_params: {}

########################################

- name: "trigger shutdown"
  debugger: never
  become: yes
  shell: "nohup bash -c 'sleep 2 && shutdown -c && shutdown -P now' &"
  async: 1
  poll: 0
  tags: reboot

- meta: reset_connection

- name: "wait for ssh connection to dissappear"
  debugger: never
  wait_for:
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    port: 22
    state: stopped
    delay: 10
    sleep: 10
  delegate_to: 127.0.0.1

###################################
#
#   tasks
#
###################################

########################################

- include_tasks:
    file: _task_footer.yml
  vars:
    kol_utils_exit_vars: []
