---
- name: "Restart ntp"
  become: yes
  systemd:
    state: restarted
    name: systemd-timesyncd
    daemon_reload: yes
  when: skip_handlers | default(False) == False

- name: "Restart iscsi server"
  become: yes
  systemd:
    state: restarted
    name: tgt
    daemon_reload: yes
  when: skip_handlers | default(False) == False

- name: "Reboot"
  include_tasks:
    file: reboot.yml
  when: skip_handlers | default(False) == False
